_ALL_LANGS = {
    "bav": "Vengo",
    "acf": "Saint Lucian Creole French",
    "frp": "Arpitan",
    "sea": "Semai",
    "atv-alt": "Northern Altai",
    "csh": "Asho Chin",
    "ddo": "Tsez",
    "ukr": "Ukrainian",
    "skd": "Southern Sierra Miwok",
    "pej": "Northern Pomo",
    "cjo-cpy": "Ash\u00e9ninka Pajonal",
    "bfu": "Bunan",
    "poi": "Highland Popoluca",
    "shp": "Shipibo-Conibo",
    "nyt": "Nyawaygi",
    "zav": "Yatzachi Zapotec",
    "kut": "Kutenai",
    "rap": "Rapanui",
    "ndh": "Ndali",
    "jup": "Hup",
    "cok-crn": "Santa Teresa Cora",
    "neb": "Toura (C\u00f4te d'Ivoire)",
    "bho": "Bhojpuri",
    "kiu": "Kirmanjki",
    "nas": "Naasioi",
    "tnc": "Tanimuca-Retuar\u00e3",
    "wsk": "Waskia",
    "tow": "Towa",
    "hsb": "Upper Sorbian",
    "rmb": "Rembarrnga",
    "bee": "Byangsi",
    "orh": "Oroqen",
    "nlg": "Gela",
    "kdr": "Karaim",
    "tby": "Tabaru",
    "tae": "Tariana",
    "der": "Deori",
    "peg": "Pengo",
    "cap": "Chipaya",
    "faa": "Fasu",
    "ykg-yu": "Northern Yukaghir",
    "kvw": "Wersing",
    "smo": "Samoan",
    "kor": "Korean",
    "dic": "Lakota Dida",
    "quh": "South Bolivian Quechua",
    "skv": "Skou",
    "yap": "Yapese",
    "dua": "Duala",
    "tbg": "North Tairora",
    "csy": "Sizang Chin",
    "aho": "Ahom",
    "khc-bhq": "Tukang Besi North",
    "srq": "Sirion\u00f3",
    "hid": "Hidatsa",
    "cac": "Chuj",
    "cir": "Tiri-Mea",
    "ace": "Acehnese",
    "hmb": "Humburi Senni Songhay",
    "zai": "Isthmus Zapotec",
    "trp": "Kok Borok",
    "idu": "Idoma",
    "cmn": "Mandarin Chinese",
    "che": "Chechen",
    "bck": "Bunaba",
    "otw": "Ottawa",
    "ati": "Atti\u00e9",
    "vut": "Vute",
    "khk": "Halh Mongolian",
    "chr": "Cherokee",
    "hna": "Mina (Cameroon)",
    "kwk": "Kwak'wala",
    "swh": "Swahili",
    "niv": "Amur Nivkh",
    "trc": "Copala Triqui",
    "ewe": "Ewe",
    "apt": "Apatani",
    "sag-sbp": "Sango",
    "one": "Oneida",
    "wac": "Upper Chinook",
    "csc": "Catalan Sign Language",
    "gma": "Gambera",
    "qwh-qxn": "Huaylas Ancash Quechua",
    "dta": "Dagur",
    "urh": "Urhobo",
    "dak": "Dakota",
    "jap": "Jaru\u00e1ra",
    "djj": "Djeebbana",
    "jeh": "Jeh",
    "slv": "Slovenian",
    "djr": "Djambarrpuyngu",
    "azb": "South Azerbaijani",
    "swb": "Maore Comorian",
    "ote": "Mezquital Otomi",
    "cak": "Kaqchikel",
    "kbk": "Grass Koiari",
    "aoa": "Angolar",
    "wga": "Wagaya",
    "ses": "Koyraboro Senni Songhai",
    "qxs-cng": "Southern Qiang",
    "thk": "Tharaka",
    "glg": "Galician",
    "cni": "Ash\u00e1ninka",
    "yor": "Yoruba",
    "yuz": "Yuracar\u00e9",
    "alr": "Alutor",
    "suk": "Sukuma",
    "tdt": "Tetun Dili",
    "ngn": "Ngwo",
    "any": "Anyin",
    "ivv": "Itbayat",
    "niy": "Ngiti",
    "ngk": "Ngalkbun",
    "pus": "Nuclear Pashto",
    "nds": "Eastern Low German",
    "ady": "Adyghe",
    "kmc": "Southern Dong",
    "cso": "Sochiapam Chinantec",
    "nly": "Nyamal",
    "jac": "Popti'",
    "itz": "Itz\u00e1",
    "kas": "Kashmiri",
    "ajp": "South Levantine Arabic",
    "yia": "Yinggarda",
    "ary": "Moroccan Arabic",
    "bbc": "Batak Toba",
    "jpn": "Japanese",
    "twf": "Taos Northern Tiwa",
    "wbv": "Wajarri",
    "dan": "Danish",
    "brc": "Berbice Creole Dutch",
    "vai": "Vai",
    "yua": "Yucatec Maya",
    "kpw": "Kobon",
    "ktg": "Kalkutung",
    "ojg-ojb": "Eastern Ojibwa",
    "urd": "Urdu",
    "kgs": "Kumbainggar",
    "chp": "Chipewyan",
    "for": "Fore",
    "pad": "Paumari",
    "des": "Desano",
    "gcr": "Guianese Creole French",
    "bod": "Tibetan",
    "pip": "Pero",
    "crs": "Seselwa Creole French",
    "adj": "Adioukrou",
    "tsj": "Tshangla",
    "non": "Old Norse",
    "bft": "Balti",
    "trv": "Seediq",
    "kir": "Kirghiz",
    "piu": "Pintupi-Luritja",
    "srb": "Sora",
    "ast": "Asturian-Leonese-Cantabrian",
    "ztu": "G\u00fcil\u00e1 Zapotec",
    "tzb-tzh": "Tzeltal, Bachaj\u00f3n",
    "kmu": "Kanite",
    "pes": "Western Farsi",
    "kjl-kip-kgj-kif": "Western Parbate Kham",
    "nuy": "Wubuy",
    "goh": "Old High German (ca. 750-1050)",
    "nir": "Nimboran",
    "ayu": "Ayu",
    "awn": "Awngi",
    "ilo": "Iloko",
    "kin": "Kinyarwanda",
    "gni": "Gooniyandi",
    "kck": "Kalanga",
    "shs": "Shuswap",
    "eng": "English",
    "kac": "Southern Jinghpaw",
    "khb": "L\u00fc",
    "bgq": "Bagri",
    "nun-nut-raw-yue": "Nung (Myanmar)",
    "nyn-cgg": "Nyankole",
    "tbo": "Tawala",
    "yab": "Yuhup",
    "enq": "Enga",
    "ssf": "Thao",
    "fro": "Old French (842-ca. 1400)",
    "sbe": "Saliba",
    "esi": "North Alaskan Inupiatun",
    "amp": "Alamblak",
    "van": "Walman",
    "did-laj-lno": "Didinga",
    "srp-hrv": "Serbian Standard",
    "kmn": "Awtuw",
    "cku": "Koasati",
    "gvn": "Kuku-Yalanji",
    "gru": "Kistane",
    "rwr": "Marwari (India)",
    "kfz": "Koromf\u00e9",
    "kpv": "Komi-Zyrian",
    "pyu": "Puyuma",
    "wrr": "Wardaman",
    "sac": "Meskwaki",
    "ted": "Tepo Krumen",
    "njo": "Ao Naga",
    "sei": "Seri",
    "kla": "Klamath-Modoc",
    "kzh": "Kenuzi-Dongola",
    "egy": "Egyptian (Ancient)",
    "bew": "Betawi",
    "tvo": "Tidore",
    "fuc": "Pulaar",
    "jek": "Jeli",
    "vls": "Western Flemish",
    "pih": "Pitcairn-Norfolk",
    "gnn": "Gumatj",
    "aer-are": "Eastern Arrernte",
    "hoa": "Hoava",
    "gbi": "Galela",
    "fuv-fub-fuq-fuh-fuc": "Hausa States Fulfulde",
    "grt": "Garo",
    "fon": "Fon",
    "kgq": "Kamoro",
    "tur": "Turkish",
    "zmu": "Muruwari",
    "cad": "Caddo",
    "dhr": "Dhargari",
    "nhg": "Tetelcingo Nahuatl",
    "bsk": "Burushaski",
    "now": "Nyambo",
    "dif": "Dieri",
    "ood": "Tohono O'odham",
    "als": "Northern Tosk Albanian",
    "gvr": "Gurung",
    "ktn": "Kariti\u00e2na",
    "amh": "Amharic",
    "nmn": "East Taa",
    "nav": "Navajo",
    "zaa": "Sierra de Ju\u00e1rez Zapotec",
    "afr": "Afrikaans",
    "wuu": "Wu Chinese",
    "guh": "Sikuani",
    "kpv-koi": "Komi-Zyrian",
    "aer": "Eastern Arrernte",
    "oia": "Oirata",
    "guw": "Gun",
    "pjt": "Pitjantjatjara",
    "krc": "Karachay-Balkar",
    "yue": "Yue Chinese",
    "fin": "Finnish",
    "osp": "Old Spanish",
    "bcr": "Witsuwit'en-Babine",
    "nay": "Narrinyeri",
    "shu": "Chadian Arabic",
    "anu": "Anuak",
    "bjh": "Bahinemo",
    "end": "Ende",
    "tsz": "Purepecha",
    "sat": "Santali",
    "agq": "Aghem",
    "gsc": "Gascon (Retired)",
    "djk": "Aukan",
    "hbb": "Huba",
    "qxo": "Southern Conchucos Ancash Quechua",
    "ryu": "Central Okinawan",
    "san": "Sanskrit",
    "tzt-tzj": "Tz'utujil, Western",
    "ksw": "S'gaw Karen",
    "ski": "Sika",
    "ekg": "Ekari",
    "ani": "Andi",
    "fao": "Faroese",
    "djd": "Jaminjung-Ngaliwurru",
    "nci": "Classical Nahuatl",
    "klu": "Klao",
    "agb": "Legbo",
    "sot": "Southern Sotho",
    "tzj-tzt": "Tz'utujil",
    "spp": "Supyire Senoufo",
    "plt": "Plateau Malagasy",
    "gyn": "Guyanese Creole English",
    "arn": "Mapudungun",
    "imn": "Imonda",
    "bot": "Bongo",
    "diq": "Dimli",
    "slp": "Lamaholot",
    "ywr": "Yawuru",
    "hae": "Eastern Oromo",
    "tri": "Tri\u00f3",
    "cha": "Chamorro",
    "pms": "Piemontese",
    "bxw-fmp": "Bankagooma",
    "ojg-otw": "Eastern Ojibwa",
    "auw": "Awyi",
    "cks": "Tayo",
    "aqc": "Archi",
    "ntp": "Northern Tepehuan",
    "rus": "Russian",
    "yak": "Northwest Sahaptin",
    "ibo": "Igbo",
    "srp": "Serbian Standard",
    "ayz": "Maybrat-Karon",
    "skb": "Saek",
    "nus": "Nuer",
    "tus": "Tuscarora",
    "ruf": "Luguru",
    "gbz": "Zoroastrian Yazdi",
    "uzb": "Uzbek",
    "gdo": "Godoberi",
    "boa": "Bora",
    "ikt": "Western Canadian Inuktitut",
    "ktz": "South-Eastern Ju",
    "qub-quz-quh-quy-qwh": "Huallaga Hu\u00e1nuco Quechua",
    "ths": "Thakali",
    "kxi": "Keningau Murut",
    "ang": "Old English (ca. 450-1100)",
    "gsg": "German Sign Language",
    "fuv-fub-fuq-fuh": "Hausa States Fulfulde",
    "eve": "Even",
    "nna": "Nyangumarta",
    "tgk": "Tajik",
    "pap": "Papiamento",
    "etu": "Ejagham",
    "rcf": "R\u00e9union Creole French",
    "jmc": "Machame",
    "huz": "Hunzib",
    "crj": "Southern East Cree",
    "wao": "Wappo",
    "oac": "Oroch",
    "dis": "Dimasa",
    "ker": "Kera",
    "dga": "Central Dagaare",
    "ike": "Eastern Canadian Inuktitut",
    "sas": "Sasak",
    "bps": "Sarangani Blaan",
    "woe": "Woleaian",
    "cop": "Coptic",
    "nia": "Nias",
    "apc": "Levantine Arabic",
    "esu": "Central Alaskan Yupik",
    "gmh": "Middle High German",
    "ple": "Palu'e",
    "str": "Northern Straits Salish",
    "qvn": "North Jun\u00edn Quechua",
    "omb": "East Ambae",
    "yih": "Western Yiddish",
    "wof": "Gambian Wolof",
    "hye": "Eastern Armenian",
    "tbc": "Takia",
    "pnb": "Western Panjabi",
    "kjq": "Western Keres",
    "ixi": "Ixil Nebaj",
    "gle": "Irish",
    "ijc": "Izon",
    "orv": "Old Russian",
    "nhe-nhw-nch-ngu-nhs-azz": "Eastern Huasteca Nahuatl",
    "bci": "Baoul\u00e9",
    "bnn": "Bunun",
    "kkk": "Kokota",
    "pnt": "Pontic",
    "cjv": "Chuave",
    "kcd": "Ngkontar Ngkolmpu",
    "yad": "Yagua",
    "nio": "Nganasan",
    "dyy": "Dyaabugay",
    "tat": "Tatar",
    "yee": "Yimas",
    "ons": "Ono",
    "alp": "Alune",
    "puw": "Puluwatese",
    "knc": "Central Kanuri",
    "pln": "Palenquero",
    "had": "Hatam",
    "ifb": "Batad Ifugao",
    "fuv": "Hausa States Fulfulde",
    "nnb": "Nande",
    "ise": "Italian Sign Language",
    "vay": "Wayu",
    "gyd": "Kayardild",
    "rab": "Camling",
    "car": "Galibi Carib",
    "kbc": "Kadiw\u00e9u",
    "snf": "Noon",
    "gbc": "Garrwan",
    "qwh": "Huaylas Ancash Quechua",
    "qvs": "San Mart\u00edn Quechua",
    "saj": "Sahu",
    "alo": "Larike-Wakasihu",
    "idb": "Daman-Diu Portuguese",
    "zap": "Zapotec",
    "tly": "North-Central Talysh",
    "wkw": "Wakawaka",
    "pbt": "Southern Pashto",
    "tzz": "Tzotzil, Zinacant\u00e1n",
    "ach": "Acoli",
    "nan": "Min Nan Chinese",
    "ian": "Iatmul",
    "gbj": "Bodo Gadaba",
    "dus": "Dumi",
    "quz": "Cusco Quechua",
    "peb": "Eastern Pomo",
    "aib-ain": "Ainu (China)",
    "iai": "Iaai",
    "pwn": "Paiwan",
    "dnw": "Western Dani",
    "rma": "Rama",
    "hit": "Hittite",
    "sza": "Semelai",
    "rog": "Northern Roglai",
    "vmw": "Makhuwa",
    "ckb": "Central Kurdish",
    "umu": "Munsee",
    "kju": "Kashaya",
    "koi": "Komi-Permyak",
    "koy": "Koyukon",
    "ojp": "Old Japanese",
    "ert": "Eritai",
    "csz": "Hanis",
    "cpu": "Pichis Ash\u00e9ninka",
    "yuf": "Havasupai-Walapai-Yavapai",
    "ase": "American Sign Language",
    "ojc": "Central Ojibwa",
    "akv": "Akhvakh",
    "fab": "Annobonese",
    "sme": "North Saami",
    "hun": "Hungarian",
    "ard-wgg": "Arabana",
    "urk": "Urak Lawoi'",
    "och": "Old Chinese",
    "ctu-cti": "Chol",
    "odt": "Old Dutch-Old Frankish",
    "apy": "Apala\u00ed",
    "cup": "Cupe\u00f1o",
    "ygr": "Yagaria",
    "bfa": "Bari",
    "tyn": "Kombai",
    "bhq-khc": "Tukang Besi South",
    "pit": "Pitta Pitta",
    "cbs": "Cashinahua",
    "nab": "Southern Nambiku\u00e1ra",
    "yai": "Yagnobi",
    "ydd": "Eastern Yiddish",
    "nez": "Nez Perce",
    "bwu": "Buli (Ghana)",
    "yaz": "Lokaa",
    "hur": "Halkomelem",
    "tpc": "Azoy\u00fa Me'phaa",
    "nhe-nhw-nch-nhs": "Eastern Huasteca Nahuatl",
    "kaz": "Kazakh",
    "onr-oin": "Northern One",
    "asb": "Assiniboine",
    "rmn": "Balkan Romani",
    "yuc": "Yuchi",
    "waw": "Waiwai",
    "pdc": "Pennsylvania German",
    "yij": "Yindjibarndi",
    "bca-bfc-bfs": "Central Bai",
    "pav": "Wari'",
    "cro": "Crow",
    "fud": "East Futuna",
    "ddj": "Jaru",
    "gue-rop": "Gurindji",
    "ojg-ojc": "Eastern Ojibwa",
    "gax-hae": "Borana-Arsi-Guji Oromo",
    "nya": "Nyanja",
    "kio": "Kiowa",
    "khq": "Koyra Chiini Songhay",
    "vec": "Venetian",
    "toi": "Tonga (Zambia)",
    "jut": "Jutish",
    "dag": "Dagbani",
    "bfa-mqu-muw-unr": "Bari",
    "acv": "Achumawi",
    "kwi": "Awa-Cuaiquer",
    "bnd": "Banda (Indonesia)",
    "tig": "Tigre",
    "pei": "Chichimeca-Jonaz",
    "tao": "Yami",
    "chg": "Chagatai",
    "kjc": "Coastal Konjo",
    "vie": "Vietnamese",
    "soq": "Kanasi",
    "rop": "Kriol",
    "bsf": "Bauchi",
    "wba": "Warao",
    "nbi": "Mao Naga",
    "pau": "Palauan",
    "gvp": "Par\u00e1-Maranh\u00e3o Gavi\u00e3o",
    "ess": "Central Siberian Yupik",
    "hbo": "Ancient Hebrew",
    "huq": "Tsat",
    "ngu": "Central Guerrero Nahuatl",
    "wno": "Wano",
    "ces": "Czech",
    "plo": "Oluta Popoluca",
    "sin": "Sinhala",
    "kjh": "Khakas",
    "esu-ess": "Central Alaskan Yupik",
    "onr-oin-aun": "Northern One",
    "nad": "Nijadali",
    "cji": "Chamalal",
    "cjs": "Shor",
    "tui": "Tupuri",
    "kea": "Kabuverdianu",
    "tuv": "Turkana",
    "gla": "Scottish Gaelic",
    "bar": "Bavarian",
    "qwh-qxn-qxo": "Huaylas Ancash Quechua",
    "bgr": "Bawm Chin",
    "twq": "Tasawaq",
    "cho": "Choctaw",
    "cng": "Northern Qiang",
    "div": "Dhivehi",
    "sgw": "Sebat Bet Gurage",
    "wmb": "Wambayan",
    "tdh": "Thulung",
    "kng": "South-Central Koongo",
    "knj": "Akateko",
    "tzc-tzz": "Tzotzil, Chamula",
    "pbu": "Northern Pashto",
    "nbc": "Chang Naga",
    "fut": "Futuna-Aniwa",
    "dni": "Lower Grand Valley Dani",
    "ksz": "Kodaku",
    "enn": "Egene",
    "sjo": "Xibe",
    "otw-ojg": "Ottawa",
    "omr": "Old Marathi",
    "bao-bsn": "Waimaha",
    "gvf": "Golin",
    "jda": "Jad",
    "fra": "French",
    "khr": "Kharia",
    "toh": "Gitonga",
    "zpi": "Santa Mar\u00eda Quiegolani Zapotec",
    "kjp": "Pwo Eastern Karen",
    "cic": "Chickasaw",
    "kek": "Kekch\u00ed",
    "kif": "Eastern Parbate Kham",
    "bxr": "Russia Buriat",
    "gvo": "Gavi\u00e3o Do Jiparan\u00e1",
    "awb": "Awa (Papua New Guinea)",
    "hay": "Haya",
    "sga": "Early Irish",
    "uma": "Umatilla",
    "pcj": "Gorum-Parenga",
    "sja": "Epena",
    "ibd": "Iwaidja",
    "yoy": "Yoy",
    "smn": "Inari Saami",
    "adg": "Andegerebinha",
    "ceb": "Cebuano",
    "wms": "Wambon",
    "kkp": "Gugubera",
    "rit": "Ritharrngu",
    "rif": "Tarifiyt-Beni-Iznasen-Eastern Middle Atlas Berber",
    "nmv": "Ngamini-Yarluyandi-Karangura",
    "dru": "Rukai",
    "udi": "Udi",
    "vot": "Votic",
    "hin-urd": "Hindi",
    "gaz-hae": "West Central Oromo",
    "pea": "Peranakan Indonesian",
    "nhe": "Eastern Huasteca Nahuatl",
    "ono": "Onondaga",
    "zab": "Western Tlacolula Valley Zapotec",
    "izi": "Izi-Ezaa-Ikwo-Mgbo",
    "tnk": "Kwamera",
    "sad": "Sandawe",
    "nor": "Norwegian",
    "naf": "Nabak",
    "ute": "Ute-Southern Paiute",
    "aly": "Alyawarr",
    "ita": "Italian",
    "hia": "Lamang",
    "abx-bdl-ccg-kte-pnq-smd-ssb-sse": "Inabaknon",
    "jya": "Northern Gyalrong",
    "roe": "Ronji",
    "deu-pdt": "German",
    "vmf": "Ostfr\u00e4nkisch",
    "tzc": "Tzotzil, Chamula",
    "dhv": "Dehu",
    "sna": "Shona",
    "ape": "Bukiyip",
    "kal-ike": "Kalaallisut",
    "chd": "Highland Oaxaca Chontal",
    "tmd": "Haruai",
    "pov": "Upper Guinea Crioulo",
    "dur": "Dii",
    "rup": "Aromanian",
    "blc": "Bella Coola",
    "brg": "Baure",
    "gbo-gec": "Northern Grebo",
    "fri": "Western Frisian (Retired)",
    "cpg": "Cappadocian Greek",
    "new": "Kathmandu Valley Newari",
    "blu": "Hmong Njua (Retired)",
    "ojg": "Eastern Ojibwa",
    "aka": "Akan",
    "ncg": "Nisga'a",
    "kpo": "Ikposo",
    "cos": "Corsican",
    "hin": "Hindi",
    "kdd": "Yankunytjatjara",
    "caa": "Chort\u00ed",
    "tar-tac": "Central Tarahumara",
    "tzj": "Tz'utujil",
    "jaa": "Madi",
    "rmy": "Vlax Romani",
    "tpi": "Tok Pisin",
    "umb": "Umbundu",
    "shh": "Shoshoni",
    "aiz": "Aari-Gayil",
    "src": "Logudorese Sardinian",
    "poq": "Texistepec Popoluca",
    "sry": "Sera",
    "ven": "Venda",
    "bae": "Bar\u00e9",
    "apu": "Apurin\u00e3",
    "ton": "Tonga (Tonga Islands)",
    "tah": "Tahitian",
    "sjr": "Siar-Lak",
    "dgz": "Daga",
    "yrk": "Tundra Nenets",
    "prq": "Ash\u00e9ninka Peren\u00e9",
    "crk": "Plains Cree",
    "bob": "Aweer",
    "dhg": "Dhangu",
    "nig": "Ngalakgan",
    "azr": "Adzera (Retired)",
    "nmf": "East-Central Tangkhul Naga",
    "ong": "Olo",
    "dgr": "Dogrib",
    "pmy": "Papuan Malay",
    "iii": "Sichuan Yi",
    "zpq": "Zoogocho Zapotec",
    "fij": "Fijian",
    "aar": "Afar",
    "klq": "Rumu",
    "tew": "Rio Grande Tewa",
    "tsn": "Tswana",
    "kva": "Bagvalal",
    "roh": "Romansh",
    "hat": "Haitian",
    "njb": "Nocte Naga",
    "guj": "Gujarati",
    "wls": "East Uvean",
    "tzb": "Tzeltal, Bachaj\u00f3n",
    "nob": "Norwegian Bokm\u00e5l",
    "spa": "Spanish",
    "kkj": "Kako",
    "kjs-kew": "East Kewa",
    "haw": "Hawaiian",
    "ruq": "Megleno Romanian",
    "gcc": "Mali",
    "gbb": "Kaytetye",
    "pbu-pbt": "Northern Pashto",
    "sur": "Mwaghavul",
    "cas": "Moset\u00e9n-Chiman\u00e9",
    "sus": "Susu",
    "hnj": "Hmong Njua",
    "zmr": "Maranunggu",
    "waa": "Northeast Sahaptin",
    "peo": "Old Persian (ca. 600-400 B.C.)",
    "ike-ka": "Eastern Canadian Inuktitut",
    "agn": "Agutaynen",
    "aeb": "Tunisian Arabic",
    "arz": "Egyptian Arabic",
    "fur": "Friulian",
    "jai": "Jakalteko, Western",
    "bos": "Bosnian Standard",
    "twu-dnk-txq-llg-rgu-row-bpz": "Termanu",
    "kgo": "Krongo",
    "aia": "Arosi",
    "tha": "Thai",
    "nhs": "Sierra Negra Nahuatl-Southeastern Puebla Nahuatl",
    "naq": "Nama (Namibia)",
    "zaw": "Mitla Zapotec",
    "jig": "Jingulu",
    "raw": "Rawang",
    "ksb": "Shambala",
    "kwb": "Baa",
    "enh": "Tundra Enets",
    "run": "Rundi",
    "ron": "Romanian",
    "wln": "Walloon",
    "stp": "Southeastern Tepehuan",
    "oma": "Omaha-Ponca",
    "cub": "Cubeo",
    "kno": "Kono (Sierra Leone)",
    "ram-xra": "Canela-Krah\u00f4",
    "cat": "Catalan",
    "wbp": "Warlpiri",
    "btg": "Gagnoa B\u00e9t\u00e9",
    "bni": "Bobangi",
    "tsu": "Tsou",
    "yur": "Yurok",
    "abq": "Abaza",
    "nge": "Ngemba",
    "knw": "North-Central Ju",
    "dds": "Donno So Dogon",
    "kna": "Dera (Nigeria)",
    "bfd": "Bafut",
    "kha": "Khasi",
    "noo": "Nootka",
    "ibb": "Ibibio",
    "amc": "Amahuaca",
    "ncb": "Central Nicobarese",
    "nup": "Nupe-Nupe-Tako",
    "wwr": "Warrwa",
    "kat": "Georgian",
    "ket": "Ket",
    "gde": "Gude",
    "byw": "Belhariya",
    "oge": "Old Georgian",
    "cay": "Cayuga",
    "pbe": "Mezontla Popoloca",
    "tik": "Tikar",
    "ben": "Bengali",
    "klj": "Turkic Khalaj",
    "scn": "Sicilian",
    "bwe": "Bwe Karen",
    "bin": "Bini",
    "sae": "Saban\u00ea",
    "ure": "Uru",
    "yux-ykg": "Southern Yukaghir",
    "gej": "Gen",
    "hwo": "Hwana",
    "dsq": "Tadaksahak",
    "nep": "Eastern Pahari",
    "ncj": "Northern Puebla Nahuatl",
    "kmb": "Kimbundu",
    "ser": "Serrano",
    "pbu-pst": "Northern Pashto",
    "wit": "Wintu",
    "ctd": "Tedim Chin",
    "ewo": "Ewondo",
    "kew-kjs": "West Kewa",
    "gkn": "Gokana",
    "emk": "Eastern Maninkakan",
    "kij": "Kilivila",
    "knk": "Kuranko",
    "cle": "Lealao Chinantec",
    "bua": "Buriat",
    "jao": "Yanyuwa",
    "tlp": "Filomeno Mata Totonac",
    "rug": "Roviana",
    "aey": "Amele",
    "thp": "Thompson",
    "nso": "Pedi",
    "ckv": "Kavalan",
    "tep": "Tepecano",
    "dap": "Dafla",
    "wae": "Walser",
    "bsn-bao-pok": "Barasana-Eduria",
    "fuv-fub": "Hausa States Fulfulde",
    "ynn": "Yana",
    "tcb": "Tanacross",
    "nhd": "Chirip\u00e1",
    "wsa": "Warembori",
    "kxa": "Kairiru",
    "eky": "Eastern Kayah",
    "pbi": "Parkwa",
    "tue": "Tuyuca",
    "prs": "Dari",
    "tiw": "Tiwi",
    "sgu": "Salas",
    "gue": "Gurindji",
    "tkr": "Tsakhur",
    "wnu": "Usan",
    "niu": "Niuean",
    "abk": "Abkhaz",
    "pmi-pmj": "Northern Pumi",
    "eus": "Basque",
    "tub": "T\u00fcbatulabal",
    "cjh": "Upper Chehalis",
    "csw": "Swampy Cree",
    "kgr": "Abun",
    "bqe": "Navarro-Labourdin Basque",
    "amk": "Ambai",
    "bbb": "Barai",
    "kan": "Kannada",
    "jav": "Javanese",
    "ogo": "Khana",
    "thd": "Thayore",
    "hau": "Hausa",
    "ckt": "Chukchi",
    "abs": "Ambonese Malay",
    "kfk": "Kinnauri",
    "baz": "Tunen (Retired)",
    "gcd": "Ganggalida",
    "kri": "Krio",
    "nld": "Dutch",
    "gax-or": "Borana-Arsi-Guji Oromo",
    "ktu": "Kituba (Democratic Republic of Congo)",
    "ppn": "Papapana",
    "kay": "Kamayur\u00e1",
    "kik": "Kikuyu",
    "tpy": "Trumai",
    "kqr": "Kimaragang",
    "jqr": "Jaqaru",
    "nyq": "Nayinic",
    "tht": "Tahltan",
    "tan": "Tangale",
    "svs": "Savosavo",
    "bak": "Bashkir",
    "crg": "Michif",
    "pan": "Eastern Panjabi",
    "par": "Panamint",
    "hch": "Huichol",
    "txg": "Tangut",
    "kwd": "Kwaio",
    "sah": "Sakha",
    "heb": "Modern Hebrew",
    "grc": "Ionic-Attic Ancient Greek",
    "bao": "Waimaha",
    "kbd": "Kabardian",
    "tyv": "Tuvinian",
    "srs": "Sarsi",
    "njh": "Lotha Naga",
    "bez": "Bena (Tanzania)",
    "ahk": "Akha",
    "yaf": "Yaka-Pelende-Lonzo",
    "ung": "Ngarinyin",
    "kmg-kup": "K\u00e2te",
    "por": "Portuguese",
    "kos": "Kosraean",
    "wbk": "Nuristani Kalasha",
    "gld": "Nanai",
    "yaq": "Yaqui",
    "deu": "German",
    "bhq": "Tukang Besi South",
    "atb": "Zaiwa",
    "nee": "N\u00eal\u00eamwa-Nixumwak",
    "pis": "Pijin",
    "ylr": "Yalarnnga",
    "kjn": "Kunjen",
    "swe": "Swedish",
    "pdo": "Padoe",
    "kmg": "K\u00e2te",
    "bhp": "Bima",
    "ain": "Hokkaido Ainu",
    "gcf": "Guadeloupe-Martinique Creole French",
    "ojw": "Western Ojibwa",
    "bin-lew": "Bini",
    "hmr": "Hmar",
    "chv": "Chuvash",
    "nuf": "Nusu",
    "kew": "West Kewa",
    "slk": "Slovak",
    "gaa": "Ga",
    "alt": "Southern Altai",
    "grb": "Liberian Grebo",
    "kmr": "Northern Kurdish",
    "ohu": "Old Hungarian",
    "nut": "Nung (Viet Nam)",
    "tpz": "Tinputz",
    "ssd": "Siroi",
    "scs": "North Slavey",
    "wyb": "Ngiyambaa",
    "gug": "Paraguayan Guaran\u00ed",
    "aph": "Athpariya",
    "abt": "Ambulas",
    "irk": "Iraqw",
    "var": "Huarijio",
    "gae": "Baniva de Maroa",
    "kpc": "Curripaco",
    "gsw": "Central Alemannic",
    "tpn": "Tupinamb\u00e1",
    "ban": "Balinese",
    "bap": "Bantawa",
    "kmh": "Kalam",
    "ojg-ojb-ojw-ojs-otw": "Eastern Ojibwa",
    "bej": "Beja",
    "jai-jac": "Jakalteko, Western",
    "evn": "Evenki",
    "uig": "Uighur",
    "crn": "El Nayar Cora",
    "tar": "Central Tarahumara",
    "pma": "Paama",
    "hdn": "Northern Haida",
    "bre": "Breton",
    "nec": "Nedebang",
    "ksh": "K\u00f6lsch",
    "efi": "Efik",
    "onr-oin-aun-onk-osu-okk": "Northern One",
    "inh": "Ingush",
    "nse": "Nsenga",
    "kky": "Guugu Yimidhirr",
    "dih": "Tipai",
    "tcg": "Tamagario",
    "ami": "Amis",
    "tir": "Tigrinya",
    "vma": "Martuthunira",
    "nid": "Ngandi",
    "ybi": "Yamphu",
    "nsz": "Nisenan",
    "quc": "K'iche'",
    "yii": "Yidi\u00f1",
    "akk": "Akkadian",
    "ape-aoj-aon": "Bukiyip",
    "quz-quh-quy-qug-qvc-qwh": "Cusco Quechua",
    "gup": "Bininj Kun-Wok",
    "apj": "Jicarilla Apache",
    "ydd-yid-yih": "Eastern Yiddish",
    "cnh": "Haka Chin",
    "kuu": "Upper Kuskokwim",
    "wau": "Waur\u00e1",
    "bor": "Bororo",
    "ksd": "Kuanua",
    "kip-kgj": "Sheshi Kham",
    "tay": "Atayal",
    "nyv": "Nyulnyul",
    "nhw-nhe": "Western Huasteca Nahuatl",
    "bmi": "Bagirmi",
    "tzh": "Tzeltal",
    "asc-cns": "Casuarina Coast Asmat",
    "kjs": "East Kewa",
    "cns": "Central Asmat",
    "dar": "North-Central Dargwa",
    "qvi": "Imbabura Highland Quichua",
    "caq": "Car Nicobarese",
    "poo": "Central Pomo",
    "hop": "Hopi",
    "ito": "Itonama",
    "ind": "Standard Indonesian",
    "sip": "Sikkimese",
    "agj": "Argobba",
    "tac": "Western Tarahumara",
    "got": "Gothic",
    "aae": "Arb\u00ebresh\u00eb Albanian",
    "hrv": "Croatian Standard",
    "ssw": "Swati",
    "ojs": "Severn Ojibwa",
    "ava": "Avar",
    "snc": "Sinaugoro",
    "kun": "Kunama",
    "qub": "Huallaga Hu\u00e1nuco Quechua",
    "srn": "Sranan Tongo",
    "god": "Godi\u00e9",
    "sva": "Svan",
    "bwi": "Baniwa do Icana",
    "sly": "Selayar",
    "swr": "Saweru",
    "cpc": "Ajy\u00edninka Apurucayali",
    "pag": "Pangasinan",
    "bis": "Bislama",
    "nog": "Nogai",
    "pua-tsz": "Western Highland Purepecha",
    "ccc": "Chamicuro",
    "pon": "Pohnpeian",
    "bla": "Siksika",
    "kca": "Kazym-Berezover-Suryskarer Khanty",
    "pnw": "Panytyima",
    "kaq": "Capanahua",
    "pbb": "P\u00e1ez",
    "aty": "Aneityum",
    "kji": "Zabana",
    "hni": "Hani",
    "tya": "Tauya",
    "yea": "Ravula",
    "quc-qut-quu": "K'iche'",
    "ude": "Udihe",
    "nno": "Norwegian Nynorsk",
    "ojb": "Northwestern Ojibwa",
    "arb": "Standard Arabic",
    "afb": "Gulf Arabic",
    "sue": "Suena",
    "adi": "Bori-Karko",
    "ale": "Aleut",
    "apr": "Arop-Lokep",
    "khe": "Korowai",
    "arh": "Arhuaco",
    "tuo": "Tucano",
    "rmw": "Welsh Romani",
    "hai": "Haida",
    "urb": "Urub\u00fa-Kaapor",
    "hmo": "Hiri Motu",
    "bqc": "Boko (Benin)",
}
